--------------------------------------------

# DAY 1
--------------------------------------------

# SESSION 1

In [2]:
print ("Hello, World")

Hello, World


# Text
* Bullet 1
+ Bullet 2


## Smaller text
### Smaller text
#### SMALLER text
##### Italic text?

In [3]:
34/12.5

2.72

In [4]:
"Brian"

'Brian'

In [5]:
bkid = "This is a string"

In [6]:
print (type(bkid), bkid)

<class 'str'> This is a string


In [7]:
h = 5.2
print (h)

5.2


In [8]:
w = 56
print (w)

56


In [9]:
bmi = w/h ** 2
print ("BMI is :", bmi)

BMI is : 2.0710059171597632


In [10]:
pi = 3.14

rad = 10

area = pi * rad ** 2

print (area)

314.0


----------------------------------------------
# SESSION 2
## NumPy

* ### Without NumPy


In [11]:
#Create List
list1 = [6.12,7.2,14.4,5.6,8.9]

#Printing list
print(type(list1),list1)

#Concat list
list_full = list1+list1

#print new list
print(list_full)

<class 'list'> [6.12, 7.2, 14.4, 5.6, 8.9]
[6.12, 7.2, 14.4, 5.6, 8.9, 6.12, 7.2, 14.4, 5.6, 8.9]


#### The + operation concatenated the 2 lists, instead of adding.

----------------------------------------------------------------
# NOW.....
* ## With NumPy

In [12]:
import numpy as np

In [13]:
nlist = np.array(list1)

In [14]:
print(type(nlist),nlist)

<class 'numpy.ndarray'> [  6.12   7.2   14.4    5.6    8.9 ]


In [15]:
list_new = nlist + nlist
print(list_new)

[ 12.24  14.4   28.8   11.2   17.8 ]


#### The + operation adds each of the corresponding items.

In [16]:
# Dimensions of array
nlist.ndim

1

In [17]:
data = [[1,3,4,5],[5,6,7,8]]

In [18]:
data

[[1, 3, 4, 5], [5, 6, 7, 8]]

In [19]:
npdata = np.array(data)

In [20]:
print(type(npdata),"Dimension:",npdata.ndim,"\nArray:", npdata)

<class 'numpy.ndarray'> Dimension: 2 
Array: [[1 3 4 5]
 [5 6 7 8]]


In [21]:
npdata.shape

(2, 4)

In [22]:
np.zeros(5), np.ones(4)

(array([ 0.,  0.,  0.,  0.,  0.]), array([ 1.,  1.,  1.,  1.]))

In [23]:
arr4 = np.array([1,2,3,4])

arr4[0:2] = np.zeros(2)

arr4

array([0, 0, 3, 4])

In [24]:
arr1 = np.arange(18).reshape(6,3)

In [25]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [26]:
arr1.dtype

dtype('int32')

In [27]:
arr2 = np.array([np.zeros(4),[1,2,3,4],np.ones(4),[5,4,3,2]])

In [28]:
arr2

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  1.,  1.,  1.],
       [ 5.,  4.,  3.,  2.]])

---------------------------------------------------------------------------------
* operations on Array


In [29]:
arr2*arr2

array([[  0.,   0.,   0.,   0.],
       [  1.,   4.,   9.,  16.],
       [  1.,   1.,   1.,   1.],
       [ 25.,  16.,   9.,   4.]])

In [30]:
arr2 = arr2+4
arr2

array([[ 4.,  4.,  4.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 5.,  5.,  5.,  5.],
       [ 9.,  8.,  7.,  6.]])

In [31]:
1/arr2

array([[ 0.25      ,  0.25      ,  0.25      ,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ],
       [ 0.2       ,  0.2       ,  0.2       ,  0.2       ],
       [ 0.11111111,  0.125     ,  0.14285714,  0.16666667]])

In [32]:
emarr = np.empty((2,3,4))

In [33]:
emarr

array([[[  1.17292082e-311,   7.75683064e-322,   0.00000000e+000,
           0.00000000e+000],
        [  1.86170116e+243,   5.02034658e+175,   4.42431019e-052,
           2.74882549e-057],
        [  1.44690071e+030,   4.76655463e-038,   1.47763641e+248,
           1.16096346e-028]],

       [[  7.69165785e+218,   1.35617292e+248,   5.94860759e+015,
           5.12306744e+025],
        [  1.04256846e+011,   1.20407817e-071,   4.26215782e-096,
           6.32299154e+233],
        [  6.48224638e+170,   5.22411352e+257,   5.74020278e+180,
           8.37174974e-144]]])

In [34]:
emarr[1][0] = np.array(range(0,4))

In [35]:
emarr

array([[[  1.17292082e-311,   7.75683064e-322,   0.00000000e+000,
           0.00000000e+000],
        [  1.86170116e+243,   5.02034658e+175,   4.42431019e-052,
           2.74882549e-057],
        [  1.44690071e+030,   4.76655463e-038,   1.47763641e+248,
           1.16096346e-028]],

       [[  0.00000000e+000,   1.00000000e+000,   2.00000000e+000,
           3.00000000e+000],
        [  1.04256846e+011,   1.20407817e-071,   4.26215782e-096,
           6.32299154e+233],
        [  6.48224638e+170,   5.22411352e+257,   5.74020278e+180,
           8.37174974e-144]]])

-------------------------------------------
# DAY 2
--------------------------------------------


# SESSION 1
--------------------------------------
## Pandas

In [40]:
import os
import pandas as pd
from pandas import Series, DataFrame

In [50]:
obj = Series([1,2,3,4,5,6,7])

In [51]:
obj.values

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [52]:
obj

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [53]:
obj.index

RangeIndex(start=0, stop=7, step=1)

In [61]:
# manual indexing
ob = Series([1,2,3,4,5], index = ['a','b','c','d','e'])

In [59]:
ob

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [62]:
# using those indices for data manipulation

ob['c'] = -40

In [63]:
ob

a     1
b     2
c   -40
d     4
e     5
dtype: int64

In [66]:
# using particular values
ob[['a','b','c']]

a     1
b     2
c   -40
dtype: int64

In [67]:
-40 in ob.values

True

In [72]:
'd' in ob

True

In [73]:
# Dictionaries {'name': value}
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [74]:
obj3 = Series(sdata)

In [75]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [76]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [77]:
obj4 = Series(sdata, index=states)

In [78]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [83]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [84]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [92]:
obj4 = obj4.fillna(45)

In [93]:
obj4

California       45.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [94]:
pd.notnull(obj4)

California    True
Ohio          True
Oregon        True
Texas         True
dtype: bool